import Foundation

enum AppLanguage: String {
    case ru
    case en
    case zh

    static var current: AppLanguage {
        let code = (Locale.preferredLanguages.first ?? "en").lowercased()
        if code.hasPrefix("ru") {
            return .ru
        }
        if code.hasPrefix("zh") {
            return .zh
        }
        return .en
    }

    var workerCode: String {
        rawValue
    }
}

enum L10n {
    static let language = AppLanguage.current

    private static let strings: [AppLanguage: [String: String]] = [
        .en: [
            "app.subtitle": "Local audio and video transcription on your Mac",
            "label.model": "Model",
            "label.language": "Language",
            "label.detectedLanguage": "Detected language",
            "title.result": "Result",
            "footer.author": "Built by Gennadiy Zakharov",
            "help.openModelFolder": "Open model folder in Finder",
            "help.deleteModel": "Delete model",
            "button.downloading": "Downloading...",
            "button.downloadModel": "Download model",
            "button.connectLocal": "Use local model",
            "button.addMedia": "Add audio/video",
            "button.transcribing": "Transcribing...",
            "button.transcribe": "Transcribe",
            "button.copyAll": "Copy all",
            "button.saveTXT": "Save TXT",
            "button.saveJSON": "Save JSON",
            "button.delete": "Delete",
            "button.cancel": "Cancel",
            "text.downloadSources": "Model download sources: %@",
            "text.fileNotSelected": "No file selected",
            "status.modelNotLoaded": "Model not connected",
            "status.ready": "Ready",
            "status.fileSelected": "Selected file: %@",
            "status.validatingModel": "Validating local model...",
            "status.localModelConnected": "Local model connected.",
            "status.modelFolderNotFound": "Model folder was not found.",
            "status.deletingModel": "Deleting model...",
            "status.modelDeleted": "Model deleted: %@",
            "status.modelUnlinked": "Model link removed: %@",
            "status.pickFileFirst": "Please select an audio or video file first.",
            "status.connectModelFirst": "Please connect a local Whisper model first.",
            "status.preparingFile": "Preparing file...",
            "status.languageNotDetected": "not detected",
            "status.transcriptionCompleted": "Transcription completed.",
            "status.copied": "Text copied to clipboard.",
            "status.noTextToSave": "Nothing to save yet.",
            "status.txtSaved": "TXT saved: %@",
            "status.txtSaveError": "TXT save error: %@",
            "status.jsonSaved": "JSON saved: %@",
            "status.jsonSaveError": "JSON save error: %@",
            "status.preparingEnvironment": "Preparing environment...",
            "status.modelDownloadedReady": "Model downloaded and ready.",
            "status.source": "Source: %@",
            "status.downloadProgress": "%.1f%% • %@ / %@",
            "status.downloadedOnly": "Downloaded: %@",
            "status.localModel": "Local model: %@",
            "status.sourceLocalFolder": "Source: user-selected local folder",
            "panel.choosePrompt": "Choose",
            "panel.downloadModelTitle": "Choose where to save the local model",
            "panel.downloadModelMessage": "Select a folder where Whisper model files will be stored. Default: Documents/GZWhisper",
            "panel.downloadModelPrompt": "Save here",
            "panel.connectModelTitle": "Select local model",
            "panel.connectModelMessage": "Choose a folder with an already downloaded faster-whisper model.",
            "panel.connectModelPrompt": "Connect",
            "panel.saveTXTTitle": "Save transcript as TXT",
            "panel.saveJSONTitle": "Save transcript as JSON",
            "alert.deleteModelTitle": "Delete model?",
            "alert.deleteDownloadedInfo": "Model files will be removed from disk.",
            "alert.deleteLinkedInfo": "Only the app link will be removed. Files on disk will stay.",
            "engine.missingWorker": "Transcription worker script is missing in the app bundle.",
            "engine.missingVenvPython": "Python executable in the app virtual environment was not found.",
            "engine.malformedResponse": "Transcription service returned an invalid response.",
            "engine.modelMissing": "Local model was not found.",
            "engine.invalidModelPath": "Invalid local model path.",
            "engine.downloadingModel": "Downloading Whisper large-v3-turbo locally...",
            "engine.validatingModel": "Validating local model...",
            "engine.transcribing": "Running local transcription...",
            "engine.creatingVenv": "Creating local Python virtual environment...",
            "engine.creatingVenvFailed": "Failed to create virtual environment.\n%@",
            "engine.installingDeps": "Installing dependencies (faster-whisper)...",
            "engine.installDepsFailed": "Failed to install Python dependencies.\n%@",
            "process.cannotLaunch": "Failed to run %@: %@",
            "media.exportUnavailable": "Failed to initialize audio extraction from video.",
            "media.exportFailed": "Audio extraction failed: %@",
            "media.exportStatus": "Export status: %d",
            "lang.auto": "Auto",
            "lang.ru": "Russian",
            "lang.en": "English",
            "lang.zh": "Chinese",
        ],
        .ru: [
            "app.subtitle": "Локальная транскрипция аудио и видео на вашем Mac",
            "label.model": "Модель",
            "label.language": "Язык",
            "label.detectedLanguage": "Определен язык",
            "title.result": "Результат",
            "footer.author": "Разработал Геннадий Захаров",
            "help.openModelFolder": "Открыть папку модели в Finder",
            "help.deleteModel": "Удалить модель",
            "button.downloading": "Загрузка...",
            "button.downloadModel": "Загрузить модель",
            "button.connectLocal": "Указать локальную",
            "button.addMedia": "Добавить аудио/видео",
            "button.transcribing": "Транскрипция...",
            "button.transcribe": "Транскрибировать",
            "button.copyAll": "Скопировать все",
            "button.saveTXT": "Сохранить TXT",
            "button.saveJSON": "Сохранить JSON",
            "button.delete": "Удалить",
            "button.cancel": "Отмена",
            "text.downloadSources": "Откуда будет скачана модель: %@",
            "text.fileNotSelected": "Файл не выбран",
            "status.modelNotLoaded": "Модель не загружена",
            "status.ready": "Готово к работе",
            "status.fileSelected": "Файл выбран: %@",
            "status.validatingModel": "Проверяю локальную модель...",
            "status.localModelConnected": "Локальная модель подключена.",
            "status.modelFolderNotFound": "Папка модели не найдена.",
            "status.deletingModel": "Удаляю модель...",
            "status.modelDeleted": "Модель удалена: %@",
            "status.modelUnlinked": "Привязка к модели удалена: %@",
            "status.pickFileFirst": "Сначала выберите аудио или видео файл.",
            "status.connectModelFirst": "Сначала подключите локальную модель Whisper.",
            "status.preparingFile": "Подготовка файла...",
            "status.languageNotDetected": "не определен",
            "status.transcriptionCompleted": "Транскрипция завершена.",
            "status.copied": "Текст скопирован в буфер обмена.",
            "status.noTextToSave": "Нет текста для сохранения.",
            "status.txtSaved": "TXT сохранен: %@",
            "status.txtSaveError": "Ошибка сохранения TXT: %@",
            "status.jsonSaved": "JSON сохранен: %@",
            "status.jsonSaveError": "Ошибка сохранения JSON: %@",
            "status.preparingEnvironment": "Подготовка окружения...",
            "status.modelDownloadedReady": "Модель загружена и готова к работе.",
            "status.source": "Источник: %@",
            "status.downloadProgress": "%.1f%% • %@ из %@",
            "status.downloadedOnly": "Загружено: %@",
            "status.localModel": "Локальная модель: %@",
            "status.sourceLocalFolder": "Источник: пользовательская локальная папка",
            "panel.choosePrompt": "Выбрать",
            "panel.downloadModelTitle": "Куда сохранить локальную модель",
            "panel.downloadModelMessage": "Выберите папку, где будут храниться файлы модели Whisper. По умолчанию: Documents/GZWhisper",
            "panel.downloadModelPrompt": "Сохранить сюда",
            "panel.connectModelTitle": "Указать локальную модель",
            "panel.connectModelMessage": "Выберите папку с уже скачанной моделью faster-whisper.",
            "panel.connectModelPrompt": "Подключить",
            "panel.saveTXTTitle": "Сохранить транскрипцию в TXT",
            "panel.saveJSONTitle": "Сохранить транскрипцию в JSON",
            "alert.deleteModelTitle": "Удалить модель?",
            "alert.deleteDownloadedInfo": "Файлы модели будут удалены с диска.",
            "alert.deleteLinkedInfo": "Будет удалена только привязка в приложении, файлы на диске останутся.",
            "engine.missingWorker": "В приложении не найден скрипт транскрипции.",
            "engine.missingVenvPython": "Локальный Python в окружении приложения не найден.",
            "engine.malformedResponse": "Сервис транскрипции вернул некорректный ответ.",
            "engine.modelMissing": "Локальная модель не найдена.",
            "engine.invalidModelPath": "Указан некорректный путь к локальной модели.",
            "engine.downloadingModel": "Скачиваю Whisper large-v3-turbo локально...",
            "engine.validatingModel": "Проверяю локальную модель...",
            "engine.transcribing": "Выполняю локальную транскрипцию...",
            "engine.creatingVenv": "Создаю локальное Python-окружение...",
            "engine.creatingVenvFailed": "Не удалось создать виртуальное окружение.\n%@",
            "engine.installingDeps": "Устанавливаю зависимости (faster-whisper)...",
            "engine.installDepsFailed": "Не удалось установить Python-зависимости.\n%@",
            "process.cannotLaunch": "Не удалось запустить %@: %@",
            "media.exportUnavailable": "Не удалось инициализировать экспорт аудио из видео.",
            "media.exportFailed": "Ошибка извлечения аудио: %@",
            "media.exportStatus": "Статус экспорта: %d",
            "lang.auto": "Авто",
            "lang.ru": "Русский",
            "lang.en": "Английский",
            "lang.zh": "Китайский",
        ],
        .zh: [
            "app.subtitle": "在您的 Mac 上进行本地音视频转写",
            "label.model": "模型",
            "label.language": "语言",
            "label.detectedLanguage": "识别语言",
            "title.result": "结果",
            "footer.author": "开发者：Gennadiy Zakharov",
            "help.openModelFolder": "在 Finder 中打开模型文件夹",
            "help.deleteModel": "删除模型",
            "button.downloading": "下载中...",
            "button.downloadModel": "下载模型",
            "button.connectLocal": "使用本地模型",
            "button.addMedia": "添加音频/视频",
            "button.transcribing": "转写中...",
            "button.transcribe": "开始转写",
            "button.copyAll": "复制全部",
            "button.saveTXT": "保存 TXT",
            "button.saveJSON": "保存 JSON",
            "button.delete": "删除",
            "button.cancel": "取消",
            "text.downloadSources": "模型下载来源：%@",
            "text.fileNotSelected": "未选择文件",
            "status.modelNotLoaded": "模型未连接",
            "status.ready": "就绪",
            "status.fileSelected": "已选择文件：%@",
            "status.validatingModel": "正在验证本地模型...",
            "status.localModelConnected": "本地模型已连接。",
            "status.modelFolderNotFound": "未找到模型文件夹。",
            "status.deletingModel": "正在删除模型...",
            "status.modelDeleted": "模型已删除：%@",
            "status.modelUnlinked": "模型链接已移除：%@",
            "status.pickFileFirst": "请先选择音频或视频文件。",
            "status.connectModelFirst": "请先连接本地 Whisper 模型。",
            "status.preparingFile": "正在准备文件...",
            "status.languageNotDetected": "未识别",
            "status.transcriptionCompleted": "转写完成。",
            "status.copied": "文本已复制到剪贴板。",
            "status.noTextToSave": "没有可保存的文本。",
            "status.txtSaved": "TXT 已保存：%@",
            "status.txtSaveError": "保存 TXT 失败：%@",
            "status.jsonSaved": "JSON 已保存：%@",
            "status.jsonSaveError": "保存 JSON 失败：%@",
            "status.preparingEnvironment": "正在准备环境...",
            "status.modelDownloadedReady": "模型已下载并可使用。",
            "status.source": "来源：%@",
            "status.downloadProgress": "%.1f%% • %@ / %@",
            "status.downloadedOnly": "已下载：%@",
            "status.localModel": "本地模型：%@",
            "status.sourceLocalFolder": "来源：用户选择的本地文件夹",
            "panel.choosePrompt": "选择",
            "panel.downloadModelTitle": "选择本地模型保存位置",
            "panel.downloadModelMessage": "请选择用于存放 Whisper 模型文件的文件夹。默认：Documents/GZWhisper",
            "panel.downloadModelPrompt": "保存到此处",
            "panel.connectModelTitle": "选择本地模型",
            "panel.connectModelMessage": "请选择已下载 faster-whisper 模型的文件夹。",
            "panel.connectModelPrompt": "连接",
            "panel.saveTXTTitle": "将转写结果保存为 TXT",
            "panel.saveJSONTitle": "将转写结果保存为 JSON",
            "alert.deleteModelTitle": "删除模型？",
            "alert.deleteDownloadedInfo": "模型文件将从磁盘中删除。",
            "alert.deleteLinkedInfo": "只会移除应用中的链接，磁盘文件会保留。",
            "engine.missingWorker": "应用包中缺少转写脚本。",
            "engine.missingVenvPython": "未找到应用虚拟环境中的 Python。",
            "engine.malformedResponse": "转写服务返回了无效响应。",
            "engine.modelMissing": "未找到本地模型。",
            "engine.invalidModelPath": "本地模型路径无效。",
            "engine.downloadingModel": "正在本地下载 Whisper large-v3-turbo...",
            "engine.validatingModel": "正在验证本地模型...",
            "engine.transcribing": "正在执行本地转写...",
            "engine.creatingVenv": "正在创建本地 Python 虚拟环境...",
            "engine.creatingVenvFailed": "创建虚拟环境失败。\n%@",
            "engine.installingDeps": "正在安装依赖（faster-whisper）...",
            "engine.installDepsFailed": "安装 Python 依赖失败。\n%@",
            "process.cannotLaunch": "无法启动 %@：%@",
            "media.exportUnavailable": "无法初始化从视频中提取音频。",
            "media.exportFailed": "提取音频失败：%@",
            "media.exportStatus": "导出状态：%d",
            "lang.auto": "自动",
            "lang.ru": "俄语",
            "lang.en": "英语",
            "lang.zh": "中文",
        ],
    ]

    static func t(_ key: String) -> String {
        strings[language]?[key] ?? strings[.en]?[key] ?? key
    }

    static func f(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: Locale.current, arguments: args)
    }

    static var transcriptionLanguageOptions: [(title: String, code: String)] {
        [
            (t("lang.auto"), "auto"),
            (t("lang.ru"), "ru"),
            (t("lang.en"), "en"),
            (t("lang.zh"), "zh"),
        ]
    }
}
