import Foundation

enum AppLanguage: String {
    case ru
    case en
    case zh

    static var current: AppLanguage {
        let code = (Locale.preferredLanguages.first ?? "en").lowercased()
        if code.hasPrefix("ru") {
            return .ru
        }
        if code.hasPrefix("zh") {
            return .zh
        }
        return .en
    }

    var workerCode: String {
        rawValue
    }
}

enum L10n {
    static let language = AppLanguage.current

    private static let strings: [AppLanguage: [String: String]] = [
        .en: [
            "app.subtitle": "Local audio and video transcription on your computer",
            "label.model": "Model",
            "label.modelSource": "Source:",
            "label.language": "Language",
            "label.detectedLanguage": "Detected language",
            "label.recordMode": "Record mode",
            "label.recording": "Recording",
            "label.transcription": "Transcription",
            "title.result": "Result",
            "title.history": "History",
            "footer.author": "Built by Gennadiy Zakharov",
            "help.openModelFolder": "Open model folder in Finder",
            "help.deleteModel": "Delete model",
            "help.openTranscript": "Show transcript file in Finder",
            "help.openAudio": "Show recorded audio file in Finder",
            "help.showRecordingHUD": "Show recording mini-window",
            "help.hideRecordingHUD": "Hide recording mini-window",
            "help.recordingOptions": "Recording behavior options",
            "help.transcribeFromHistory": "Queue file for transcription",
            "help.transcribeSelected": "Transcribe selected history item",
            "help.removeFromQueue": "Remove from queue",
            "help.moveQueueUp": "Move earlier in queue",
            "help.moveQueueDown": "Move later in queue",
            "help.pauseAfterCurrent": "Pause queue after the current file finishes",
            "help.skipCurrent": "Skip current file and move it to the end of the queue",
            "help.clearQueue": "Clear waiting queue items",
            "help.renameHistoryItem": "Rename entry in history",
            "help.badgeTranscript": "transcript",
            "help.badgeTranscriptAudio": "transcript + audio",
            "help.badgeAudio": "audio",
            "button.downloading": "Downloading...",
            "button.downloadModel": "Download model",
            "button.connectLocal": "Use local model",
            "button.addMedia": "Add audio/video",
            "button.startRecording": "Start recording",
            "button.stopRecording": "Stop",
            "button.pauseRecording": "Pause",
            "button.resumeRecording": "Resume",
            "button.recordingOptions": "Options",
            "button.transcribing": "Transcribing...",
            "button.transcribe": "Transcribe",
            "button.transcribeAll": "Transcribe all",
            "button.transcribeSelected": "Transcribe selected",
            "button.transcribingAll": "Transcribing queue...",
            "button.resumeQueue": "Resume queue",
            "button.pauseAfterCurrent": "Pause after current",
            "button.cancelPauseAfterCurrent": "Keep going",
            "button.skipCurrent": "Skip current",
            "button.clearQueue": "Clear queue",
            "button.queueActions": "Queue",
            "button.cancelQueue": "Cancel queue",
            "button.hideHistory": "Hide history",
            "button.showHistory": "Show history",
            "button.debug": "Debug",
            "button.copyDebugInfo": "Copy diagnostics",
            "button.openRuntimeFolder": "Open app data",
            "button.copyAll": "Copy all",
            "button.saveTXT": "Save TXT",
            "button.saveJSON": "Save JSON",
            "button.export": "Export",
            "button.delete": "Delete",
            "button.cancel": "Cancel",
            "button.undo": "Undo",
            "text.downloadSources": "Model download sources: %@",
            "text.fileNotSelected": "No file selected",
            "status.modelNotLoaded": "Model not connected",
            "status.ready": "Ready",
            "status.fileSelected": "Selected file: %@",
            "status.validatingModel": "Validating local model...",
            "status.localModelConnected": "Local model connected.",
            "status.modelFolderNotFound": "Model folder was not found.",
            "status.deletingModel": "Deleting model...",
            "status.modelDeleted": "Model deleted: %@",
            "status.modelUnlinked": "Model link removed: %@",
            "status.pickFileFirst": "Please select an audio or video file first.",
            "status.connectModelFirst": "Please connect a local Whisper model first.",
            "status.preparingFile": "Preparing file...",
            "status.languageNotDetected": "not detected",
            "status.transcriptionCompleted": "Transcription completed.",
            "status.copied": "Text copied to clipboard.",
            "status.noTextToSave": "Nothing to save yet.",
            "status.txtSaved": "TXT saved: %@",
            "status.txtSaveError": "TXT save error: %@",
            "status.jsonSaved": "JSON saved: %@",
            "status.jsonSaveError": "JSON save error: %@",
            "status.preparingEnvironment": "Preparing environment...",
            "status.modelDownloadedReady": "Model downloaded and ready.",
            "status.source": "Source: %@",
            "status.downloadProgress": "%.1f%% • %@ / %@",
            "status.downloadedOnly": "Downloaded: %@",
            "status.localModel": "Local model: %@",
            "status.sourceLocalFolder": "user-selected local folder",
            "status.filesAdded": "Files added: %d",
            "status.filesAddedLargeWarning": "Files added: %d. Large media detected: %d. On weaker Macs extraction and transcription can take longer and heat the system.",
            "status.queueEmpty": "There are no files in queue.",
            "status.queueCompleted": "Queue completed.",
            "status.queuePaused": "Queue paused.",
            "status.queuePauseRequested": "Queue will pause after the current file.",
            "status.queuePauseCancelled": "Queue will continue after the current file.",
            "status.queueSkippingCurrent": "Skipping current file...",
            "status.queueSkippedCurrent": "Skipped and moved to the end: %@",
            "status.queueCleared": "Cleared queued files: %d",
            "status.queueRemoved": "Removed from queue: %@",
            "status.queueCancelling": "Cancelling queue...",
            "status.queueCancelled": "Queue cancelled.",
            "status.transcribingFile": "Transcribing: %@",
            "status.transcriptionCompletedFile": "Completed: %@",
            "status.transcriptionProgress": "%.0f%% • %@",
            "status.historyLoaded": "Loaded from history: %@",
            "status.historyDeleted": "Removed from history: %@",
            "status.historyRestored": "Restored: %@",
            "status.historyDeleteBlocked": "Cannot delete a file while it is being transcribed.",
            "status.historyRenamed": "History entry renamed: %@",
            "status.historyRenameReset": "Original history name restored: %@",
            "status.debugCopied": "Diagnostics copied to clipboard.",
            "record.status.starting": "Starting recording...",
            "record.status.recording": "Recording in progress...",
            "record.status.paused": "Recording paused.",
            "record.status.stopping": "Stopping recording...",
            "record.status.saved": "Recording saved: %@",
            "record.status.recovered": "Recovered recording: %@",
            "record.status.recoverFailed": "Failed to recover recording: %@",
            "record.status.pausedBySystem": "Recording paused before sleep.",
            "record.status.noAudioFile": "Audio file was not found.",
            "record.status.stopFirst": "Stop recording first.",
            "record.mode.systemMic": "System + microphone",
            "record.mode.mic": "Microphone only",
            "record.mode.system": "System audio only",
            "record.mode.short.systemMic": "sys+mic",
            "record.mode.short.mic": "mic",
            "record.mode.short.system": "sys",
            "setting.hudAutoShow": "Show mini-window on start",
            "setting.autoPauseSleep": "Pause recording on sleep",
            "record.error.alreadyRecording": "Recording is already active.",
            "record.error.notRecording": "No active recording.",
            "record.error.invalidState": "Recording action is not available right now.",
            "record.error.microphoneDenied": "Microphone access was denied. Enable GZWhisper in System Settings > Privacy & Security > Microphone, then restart the app.",
            "record.error.screenDenied": "Screen recording access was denied. Enable GZWhisper in System Settings > Privacy & Security > Screen & System Audio Recording, then restart the app.",
            "record.error.screenUnavailable": "System audio recording requires macOS 13 or newer.",
            "record.error.noDisplay": "No display is available for system audio capture.",
            "record.error.writerCreate": "Cannot prepare audio writer: %@",
            "record.error.capture": "Audio capture failed: %@",
            "record.error.writer": "Audio writer failed: %@",
            "record.error.merge": "Audio merge failed: %@",
            "record.error.empty": "Recording is empty.",
            "status.unsupportedFiles": "No supported audio/video files were added.",
            "status.noTranscriptFile": "Transcript file was not found.",
            "status.fileMissing": "File is missing: %@",
            "status.readyToQueue": "Ready",
            "status.queued": "Queued",
            "status.processing": "Processing",
            "status.completed": "Completed",
            "status.failed": "Failed",
            "status.unknownDuration": "--:--:--",
            "status.eta": "ETA %@",
            "status.queuePosition": "#%d in queue",
            "text.dropFiles": "Drop audio/video files here",
            "text.historyEmpty": "History is empty. Add files and run transcription.",
            "text.historySearchEmpty": "No history entries matched your search.",
            "text.queueEmpty": "Queue is empty",
            "text.queueSingle": "1 file in queue",
            "text.queueMany": "%d files in queue",
            "placeholder.historySearch": "Search history",
            "panel.choosePrompt": "Choose",
            "panel.downloadModelTitle": "Choose where to save the local model",
            "panel.downloadModelMessage": "Select a folder where Whisper model files will be stored. Default: Documents/GZWhisper",
            "panel.downloadModelPrompt": "Save here",
            "panel.connectModelTitle": "Select local model",
            "panel.connectModelMessage": "Choose a folder with an already downloaded faster-whisper model.",
            "panel.connectModelPrompt": "Connect",
            "panel.saveTXTTitle": "Save transcript as TXT",
            "panel.saveJSONTitle": "Save transcript as JSON",
            "alert.deleteModelTitle": "Delete model?",
            "alert.deleteDownloadedInfo": "Model files will be removed from disk.",
            "alert.deleteLinkedInfo": "Only the app link will be removed. Files on disk will stay.",
            "engine.missingWorker": "Transcription worker script is missing in the app bundle.",
            "engine.missingBootstrapPython": "Python runtime was not found in the app package. Reinstall GZWhisper.",
            "engine.missingVenvPython": "Python executable in the app virtual environment was not found.",
            "engine.malformedResponse": "Transcription service returned an invalid response.",
            "engine.modelMissing": "Local model was not found.",
            "engine.invalidModelPath": "Invalid local model path.",
            "engine.downloadingModel": "Downloading Whisper large-v3-turbo locally...",
            "engine.validatingModel": "Validating local model...",
            "engine.transcribing": "Running local transcription...",
            "engine.creatingVenv": "Creating local Python virtual environment...",
            "engine.creatingVenvFailed": "Failed to create virtual environment.\n%@",
            "engine.installingDeps": "Installing dependencies (faster-whisper)...",
            "engine.installDepsFailed": "Failed to install Python dependencies.\n%@",
            "engine.offlineInstallFailed": "Bundled offline installation failed:\n%@",
            "engine.onlineInstallFailed": "Online installation from PyPI failed:\n%@",
            "engine.noProcessOutput": "The installer returned no diagnostic output.",
            "process.cannotLaunch": "Failed to run %@: %@",
            "media.noAudioTrack": "This video has no audio track. Choose a file that includes audio.",
            "media.exportUnavailable": "Failed to initialize audio extraction from video.",
            "media.exportFailed": "Audio extraction failed: %@",
            "media.exportStatus": "Export status: %d",
            "lang.auto": "Auto",
            "lang.ru": "Russian",
            "lang.en": "English",
            "lang.zh": "Chinese",
        ],
        .ru: [
            "app.subtitle": "Локальная транскрипция аудио и видео на вашем компьютере",
            "label.model": "Модель",
            "label.modelSource": "Источник:",
            "label.language": "Язык",
            "label.detectedLanguage": "Определен язык",
            "label.recordMode": "Режим записи",
            "label.recording": "Запись",
            "label.transcription": "Транскрипция",
            "title.result": "Результат",
            "title.history": "История",
            "footer.author": "Разработал Геннадий Захаров",
            "help.openModelFolder": "Открыть папку модели в Finder",
            "help.deleteModel": "Удалить модель",
            "help.openTranscript": "Показать файл транскрипта в Finder",
            "help.openAudio": "Показать аудиофайл в Finder",
            "help.showRecordingHUD": "Показать мини-окно записи",
            "help.hideRecordingHUD": "Скрыть мини-окно записи",
            "help.recordingOptions": "Параметры поведения записи",
            "help.transcribeFromHistory": "Поставить файл в очередь на транскрибацию",
            "help.transcribeSelected": "Транскрибировать выбранную запись",
            "help.removeFromQueue": "Убрать из очереди",
            "help.moveQueueUp": "Переместить выше в очереди",
            "help.moveQueueDown": "Переместить ниже в очереди",
            "help.pauseAfterCurrent": "Поставить очередь на паузу после текущего файла",
            "help.skipCurrent": "Пропустить текущий файл и перенести его в конец очереди",
            "help.clearQueue": "Очистить ожидающие элементы очереди",
            "help.renameHistoryItem": "Переименовать запись в истории",
            "help.badgeTranscript": "transcript",
            "help.badgeTranscriptAudio": "transcript + audio",
            "help.badgeAudio": "audio",
            "button.downloading": "Загрузка...",
            "button.downloadModel": "Загрузить модель",
            "button.connectLocal": "Указать локальную",
            "button.addMedia": "Добавить аудио/видео",
            "button.startRecording": "Начать запись",
            "button.stopRecording": "Стоп",
            "button.pauseRecording": "Пауза",
            "button.resumeRecording": "Продолжить",
            "button.recordingOptions": "Параметры",
            "button.transcribing": "Транскрипция...",
            "button.transcribe": "Транскрибировать",
            "button.transcribeAll": "Транскрибировать все",
            "button.transcribeSelected": "Транскрибировать выбранный",
            "button.transcribingAll": "Транскрибирую очередь...",
            "button.resumeQueue": "Продолжить очередь",
            "button.pauseAfterCurrent": "Пауза после текущего",
            "button.cancelPauseAfterCurrent": "Продолжать",
            "button.skipCurrent": "Пропустить текущий",
            "button.clearQueue": "Очистить очередь",
            "button.queueActions": "Очередь",
            "button.cancelQueue": "Отменить очередь",
            "button.hideHistory": "Скрыть историю",
            "button.showHistory": "Показать историю",
            "button.debug": "Дебаг",
            "button.copyDebugInfo": "Скопировать диагностику",
            "button.openRuntimeFolder": "Открыть папку данных",
            "button.copyAll": "Скопировать все",
            "button.saveTXT": "Сохранить TXT",
            "button.saveJSON": "Сохранить JSON",
            "button.export": "Экспорт",
            "button.delete": "Удалить",
            "button.undo": "Вернуть",
            "button.cancel": "Отмена",
            "text.downloadSources": "Откуда будет скачана модель: %@",
            "text.fileNotSelected": "Файл не выбран",
            "status.modelNotLoaded": "Модель не загружена",
            "status.ready": "Готово к работе",
            "status.fileSelected": "Файл выбран: %@",
            "status.validatingModel": "Проверяю локальную модель...",
            "status.localModelConnected": "Локальная модель подключена.",
            "status.modelFolderNotFound": "Папка модели не найдена.",
            "status.deletingModel": "Удаляю модель...",
            "status.modelDeleted": "Модель удалена: %@",
            "status.modelUnlinked": "Привязка к модели удалена: %@",
            "status.pickFileFirst": "Сначала выберите аудио или видео файл.",
            "status.connectModelFirst": "Сначала подключите локальную модель Whisper.",
            "status.preparingFile": "Подготовка файла...",
            "status.languageNotDetected": "не определен",
            "status.transcriptionCompleted": "Транскрипция завершена.",
            "status.copied": "Текст скопирован в буфер обмена.",
            "status.noTextToSave": "Нет текста для сохранения.",
            "status.txtSaved": "TXT сохранен: %@",
            "status.txtSaveError": "Ошибка сохранения TXT: %@",
            "status.jsonSaved": "JSON сохранен: %@",
            "status.jsonSaveError": "Ошибка сохранения JSON: %@",
            "status.preparingEnvironment": "Подготовка окружения...",
            "status.modelDownloadedReady": "Модель загружена и готова к работе.",
            "status.source": "Источник: %@",
            "status.downloadProgress": "%.1f%% • %@ из %@",
            "status.downloadedOnly": "Загружено: %@",
            "status.localModel": "Локальная модель: %@",
            "status.sourceLocalFolder": "пользовательская локальная папка",
            "status.filesAdded": "Файлов добавлено: %d",
            "status.filesAddedLargeWarning": "Файлов добавлено: %d. Обнаружены тяжелые медиафайлы: %d. На слабых Mac извлечение аудио и транскрибация могут идти дольше и вызывать нагрев.",
            "status.queueEmpty": "В очереди нет файлов.",
            "status.queueCompleted": "Очередь завершена.",
            "status.queuePaused": "Очередь на паузе.",
            "status.queuePauseRequested": "Очередь остановится после текущего файла.",
            "status.queuePauseCancelled": "Очередь продолжится после текущего файла.",
            "status.queueSkippingCurrent": "Пропускаю текущий файл...",
            "status.queueSkippedCurrent": "Пропущен и перенесен в конец: %@",
            "status.queueCleared": "Очищено файлов в очереди: %d",
            "status.queueRemoved": "Убрано из очереди: %@",
            "status.queueCancelling": "Отменяю очередь...",
            "status.queueCancelled": "Очередь отменена.",
            "status.transcribingFile": "Транскрибирую: %@",
            "status.transcriptionCompletedFile": "Готово: %@",
            "status.transcriptionProgress": "%.0f%% • %@",
            "status.historyLoaded": "Загружено из истории: %@",
            "status.historyDeleted": "Удалено из истории: %@",
            "status.historyRestored": "Восстановлено: %@",
            "status.historyDeleteBlocked": "Нельзя удалить файл во время транскрипции.",
            "status.historyRenamed": "Запись в истории переименована: %@",
            "status.historyRenameReset": "Возвращено исходное имя: %@",
            "status.debugCopied": "Диагностика скопирована в буфер обмена.",
            "record.status.starting": "Запускаю запись...",
            "record.status.recording": "Идет запись...",
            "record.status.paused": "Запись на паузе.",
            "record.status.stopping": "Останавливаю запись...",
            "record.status.saved": "Запись сохранена: %@",
            "record.status.recovered": "Запись восстановлена: %@",
            "record.status.recoverFailed": "Не удалось восстановить запись: %@",
            "record.status.pausedBySystem": "Перед режимом сна запись поставлена на паузу.",
            "record.status.noAudioFile": "Аудиофайл не найден.",
            "record.status.stopFirst": "Сначала остановите запись.",
            "record.mode.systemMic": "Система + микрофон",
            "record.mode.mic": "Только микрофон",
            "record.mode.system": "Только системный звук",
            "record.mode.short.systemMic": "сист+мик",
            "record.mode.short.mic": "мик",
            "record.mode.short.system": "сист",
            "setting.hudAutoShow": "Показывать мини-окно при старте",
            "setting.autoPauseSleep": "Ставить запись на паузу при сне",
            "record.error.alreadyRecording": "Запись уже запущена.",
            "record.error.notRecording": "Активной записи нет.",
            "record.error.invalidState": "Это действие сейчас недоступно.",
            "record.error.microphoneDenied": "Нет доступа к микрофону. Включите GZWhisper в Системных настройках > Конфиденциальность и безопасность > Микрофон, затем перезапустите приложение.",
            "record.error.screenDenied": "Нет доступа к записи экрана. Включите GZWhisper в Системных настройках > Конфиденциальность и безопасность > Запись экрана и системного звука, затем перезапустите приложение.",
            "record.error.screenUnavailable": "Запись системного звука доступна только на macOS 13 и новее.",
            "record.error.noDisplay": "Не найден экран для захвата системного звука.",
            "record.error.writerCreate": "Не удалось подготовить запись аудио: %@",
            "record.error.capture": "Ошибка захвата аудио: %@",
            "record.error.writer": "Ошибка записи аудио: %@",
            "record.error.merge": "Ошибка объединения аудио: %@",
            "record.error.empty": "Запись пустая.",
            "status.unsupportedFiles": "Не добавлено ни одного поддерживаемого аудио/видео файла.",
            "status.noTranscriptFile": "Файл транскрипта не найден.",
            "status.fileMissing": "Файл отсутствует: %@",
            "status.readyToQueue": "Готов к очереди",
            "status.queued": "В очереди",
            "status.processing": "В работе",
            "status.completed": "Готово",
            "status.failed": "Ошибка",
            "status.unknownDuration": "--:--:--",
            "status.eta": "Осталось %@",
            "status.queuePosition": "№%d в очереди",
            "text.dropFiles": "Перетащите сюда аудио/видео файлы",
            "text.historyEmpty": "История пуста. Добавьте файлы и запустите транскрибацию.",
            "text.historySearchEmpty": "По этому запросу ничего не найдено в истории.",
            "text.queueEmpty": "Очередь пуста",
            "text.queueSingle": "1 файл в очереди",
            "text.queueMany": "%d файлов в очереди",
            "placeholder.historySearch": "Поиск по истории",
            "panel.choosePrompt": "Выбрать",
            "panel.downloadModelTitle": "Куда сохранить локальную модель",
            "panel.downloadModelMessage": "Выберите папку, где будут храниться файлы модели Whisper. По умолчанию: Documents/GZWhisper",
            "panel.downloadModelPrompt": "Сохранить сюда",
            "panel.connectModelTitle": "Указать локальную модель",
            "panel.connectModelMessage": "Выберите папку с уже скачанной моделью faster-whisper.",
            "panel.connectModelPrompt": "Подключить",
            "panel.saveTXTTitle": "Сохранить транскрипцию в TXT",
            "panel.saveJSONTitle": "Сохранить транскрипцию в JSON",
            "alert.deleteModelTitle": "Удалить модель?",
            "alert.deleteDownloadedInfo": "Файлы модели будут удалены с диска.",
            "alert.deleteLinkedInfo": "Будет удалена только привязка в приложении, файлы на диске останутся.",
            "engine.missingWorker": "В приложении не найден скрипт транскрипции.",
            "engine.missingBootstrapPython": "В пакете приложения не найден Python runtime. Переустановите GZWhisper.",
            "engine.missingVenvPython": "Локальный Python в окружении приложения не найден.",
            "engine.malformedResponse": "Сервис транскрипции вернул некорректный ответ.",
            "engine.modelMissing": "Локальная модель не найдена.",
            "engine.invalidModelPath": "Указан некорректный путь к локальной модели.",
            "engine.downloadingModel": "Скачиваю Whisper large-v3-turbo локально...",
            "engine.validatingModel": "Проверяю локальную модель...",
            "engine.transcribing": "Выполняю локальную транскрипцию...",
            "engine.creatingVenv": "Создаю локальное Python-окружение...",
            "engine.creatingVenvFailed": "Не удалось создать виртуальное окружение.\n%@",
            "engine.installingDeps": "Устанавливаю зависимости (faster-whisper)...",
            "engine.installDepsFailed": "Не удалось установить Python-зависимости.\n%@",
            "engine.offlineInstallFailed": "Ошибка установки из встроенного офлайн-набора:\n%@",
            "engine.onlineInstallFailed": "Ошибка установки из PyPI через интернет:\n%@",
            "engine.noProcessOutput": "Установщик не вернул диагностических данных.",
            "process.cannotLaunch": "Не удалось запустить %@: %@",
            "media.noAudioTrack": "В этом видео нет аудиодорожки. Выберите файл, в котором есть аудио.",
            "media.exportUnavailable": "Не удалось инициализировать экспорт аудио из видео.",
            "media.exportFailed": "Ошибка извлечения аудио: %@",
            "media.exportStatus": "Статус экспорта: %d",
            "lang.auto": "Авто",
            "lang.ru": "Русский",
            "lang.en": "Английский",
            "lang.zh": "Китайский",
        ],
        .zh: [
            "app.subtitle": "在您的电脑上进行本地音视频转写",
            "label.model": "模型",
            "label.modelSource": "来源：",
            "label.language": "语言",
            "label.detectedLanguage": "识别语言",
            "label.recordMode": "录音模式",
            "label.recording": "录音",
            "label.transcription": "转写",
            "title.result": "结果",
            "title.history": "历史",
            "footer.author": "开发者：Gennadiy Zakharov",
            "help.openModelFolder": "在 Finder 中打开模型文件夹",
            "help.deleteModel": "删除模型",
            "help.openTranscript": "在 Finder 中显示转写文件",
            "help.openAudio": "在 Finder 中显示录音文件",
            "help.showRecordingHUD": "显示录音迷你窗口",
            "help.hideRecordingHUD": "隐藏录音迷你窗口",
            "help.recordingOptions": "录音行为选项",
            "help.transcribeFromHistory": "将文件加入转写队列",
            "help.transcribeSelected": "转写选中的历史记录",
            "help.removeFromQueue": "从队列中移除",
            "help.moveQueueUp": "在队列中前移",
            "help.moveQueueDown": "在队列中后移",
            "help.pauseAfterCurrent": "当前文件完成后暂停队列",
            "help.skipCurrent": "跳过当前文件并移到队列末尾",
            "help.clearQueue": "清除等待中的队列项目",
            "help.renameHistoryItem": "重命名历史记录条目",
            "help.badgeTranscript": "transcript",
            "help.badgeTranscriptAudio": "transcript + audio",
            "help.badgeAudio": "audio",
            "button.downloading": "下载中...",
            "button.downloadModel": "下载模型",
            "button.connectLocal": "使用本地模型",
            "button.addMedia": "添加音频/视频",
            "button.startRecording": "开始录音",
            "button.stopRecording": "停止",
            "button.pauseRecording": "暂停",
            "button.resumeRecording": "继续",
            "button.recordingOptions": "选项",
            "button.transcribing": "转写中...",
            "button.transcribe": "开始转写",
            "button.transcribeAll": "转写全部",
            "button.transcribeSelected": "转写选中项",
            "button.transcribingAll": "队列转写中...",
            "button.resumeQueue": "继续队列",
            "button.pauseAfterCurrent": "当前完成后暂停",
            "button.cancelPauseAfterCurrent": "继续执行",
            "button.skipCurrent": "跳过当前",
            "button.clearQueue": "清空队列",
            "button.queueActions": "队列",
            "button.cancelQueue": "取消队列",
            "button.hideHistory": "隐藏历史",
            "button.showHistory": "显示历史",
            "button.debug": "调试",
            "button.copyDebugInfo": "复制诊断信息",
            "button.openRuntimeFolder": "打开应用数据目录",
            "button.copyAll": "复制全部",
            "button.saveTXT": "保存 TXT",
            "button.saveJSON": "保存 JSON",
            "button.export": "导出",
            "button.delete": "删除",
            "button.cancel": "取消",
            "button.undo": "撤销",
            "text.downloadSources": "模型下载来源：%@",
            "text.fileNotSelected": "未选择文件",
            "status.modelNotLoaded": "模型未连接",
            "status.ready": "就绪",
            "status.fileSelected": "已选择文件：%@",
            "status.validatingModel": "正在验证本地模型...",
            "status.localModelConnected": "本地模型已连接。",
            "status.modelFolderNotFound": "未找到模型文件夹。",
            "status.deletingModel": "正在删除模型...",
            "status.modelDeleted": "模型已删除：%@",
            "status.modelUnlinked": "模型链接已移除：%@",
            "status.pickFileFirst": "请先选择音频或视频文件。",
            "status.connectModelFirst": "请先连接本地 Whisper 模型。",
            "status.preparingFile": "正在准备文件...",
            "status.languageNotDetected": "未识别",
            "status.transcriptionCompleted": "转写完成。",
            "status.copied": "文本已复制到剪贴板。",
            "status.noTextToSave": "没有可保存的文本。",
            "status.txtSaved": "TXT 已保存：%@",
            "status.txtSaveError": "保存 TXT 失败：%@",
            "status.jsonSaved": "JSON 已保存：%@",
            "status.jsonSaveError": "保存 JSON 失败：%@",
            "status.preparingEnvironment": "正在准备环境...",
            "status.modelDownloadedReady": "模型已下载并可使用。",
            "status.source": "来源：%@",
            "status.downloadProgress": "%.1f%% • %@ / %@",
            "status.downloadedOnly": "已下载：%@",
            "status.localModel": "本地模型：%@",
            "status.sourceLocalFolder": "用户选择的本地文件夹",
            "status.filesAdded": "已添加文件：%d",
            "status.filesAddedLargeWarning": "已添加文件：%d。检测到大体积媒体文件：%d。在性能较弱的 Mac 上，提取音频和转写会更慢，也可能导致发热。",
            "status.queueEmpty": "队列中没有文件。",
            "status.queueCompleted": "队列已完成。",
            "status.queuePaused": "队列已暂停。",
            "status.queuePauseRequested": "当前文件完成后将暂停队列。",
            "status.queuePauseCancelled": "当前文件完成后队列将继续。",
            "status.queueSkippingCurrent": "正在跳过当前文件...",
            "status.queueSkippedCurrent": "已跳过并移到末尾：%@",
            "status.queueCleared": "已清除队列文件：%d",
            "status.queueRemoved": "已从队列移除：%@",
            "status.queueCancelling": "正在取消队列...",
            "status.queueCancelled": "队列已取消。",
            "status.transcribingFile": "正在转写：%@",
            "status.transcriptionCompletedFile": "已完成：%@",
            "status.transcriptionProgress": "%.0f%% • %@",
            "status.historyLoaded": "已从历史加载：%@",
            "status.historyDeleted": "已从历史删除：%@",
            "status.historyRestored": "已恢复：%@",
            "status.historyDeleteBlocked": "文件转写中，无法删除。",
            "status.historyRenamed": "历史记录已重命名：%@",
            "status.historyRenameReset": "已恢复原始名称：%@",
            "status.debugCopied": "诊断信息已复制到剪贴板。",
            "record.status.starting": "正在启动录音...",
            "record.status.recording": "正在录音...",
            "record.status.paused": "录音已暂停。",
            "record.status.stopping": "正在停止录音...",
            "record.status.saved": "录音已保存：%@",
            "record.status.recovered": "已恢复录音：%@",
            "record.status.recoverFailed": "恢复录音失败：%@",
            "record.status.pausedBySystem": "进入睡眠前已暂停录音。",
            "record.status.noAudioFile": "未找到录音文件。",
            "record.status.stopFirst": "请先停止录音。",
            "record.mode.systemMic": "系统声音 + 麦克风",
            "record.mode.mic": "仅麦克风",
            "record.mode.system": "仅系统声音",
            "record.mode.short.systemMic": "系统+麦克风",
            "record.mode.short.mic": "麦克风",
            "record.mode.short.system": "系统",
            "setting.hudAutoShow": "开始时显示迷你窗口",
            "setting.autoPauseSleep": "系统睡眠时暂停录音",
            "record.error.alreadyRecording": "录音已在进行中。",
            "record.error.notRecording": "当前没有进行中的录音。",
            "record.error.invalidState": "当前状态无法执行此操作。",
            "record.error.microphoneDenied": "麦克风权限被拒绝。请在系统设置 > 隐私与安全性 > 麦克风中启用 GZWhisper，然后重新启动应用。",
            "record.error.screenDenied": "屏幕录制权限被拒绝。请在系统设置 > 隐私与安全性 > 屏幕与系统音频录制中启用 GZWhisper，然后重新启动应用。",
            "record.error.screenUnavailable": "系统音频录制需要 macOS 13 或更高版本。",
            "record.error.noDisplay": "未找到可用于采集系统声音的显示器。",
            "record.error.writerCreate": "无法初始化音频写入器：%@",
            "record.error.capture": "音频采集失败：%@",
            "record.error.writer": "音频写入失败：%@",
            "record.error.merge": "音频合并失败：%@",
            "record.error.empty": "录音为空。",
            "status.unsupportedFiles": "没有添加支持的音频/视频文件。",
            "status.noTranscriptFile": "未找到转写文件。",
            "status.fileMissing": "文件缺失：%@",
            "status.readyToQueue": "就绪",
            "status.queued": "排队中",
            "status.processing": "处理中",
            "status.completed": "已完成",
            "status.failed": "失败",
            "status.unknownDuration": "--:--:--",
            "status.eta": "预计剩余 %@",
            "status.queuePosition": "队列第 %d 项",
            "text.dropFiles": "将音频/视频文件拖到这里",
            "text.historyEmpty": "历史为空。添加文件后开始转写。",
            "text.historySearchEmpty": "历史记录中没有匹配的结果。",
            "text.queueEmpty": "队列为空",
            "text.queueSingle": "队列中 1 个文件",
            "text.queueMany": "队列中 %d 个文件",
            "placeholder.historySearch": "搜索历史记录",
            "panel.choosePrompt": "选择",
            "panel.downloadModelTitle": "选择本地模型保存位置",
            "panel.downloadModelMessage": "请选择用于存放 Whisper 模型文件的文件夹。默认：Documents/GZWhisper",
            "panel.downloadModelPrompt": "保存到此处",
            "panel.connectModelTitle": "选择本地模型",
            "panel.connectModelMessage": "请选择已下载 faster-whisper 模型的文件夹。",
            "panel.connectModelPrompt": "连接",
            "panel.saveTXTTitle": "将转写结果保存为 TXT",
            "panel.saveJSONTitle": "将转写结果保存为 JSON",
            "alert.deleteModelTitle": "删除模型？",
            "alert.deleteDownloadedInfo": "模型文件将从磁盘中删除。",
            "alert.deleteLinkedInfo": "只会移除应用中的链接，磁盘文件会保留。",
            "engine.missingWorker": "应用包中缺少转写脚本。",
            "engine.missingBootstrapPython": "应用包中未找到 Python 运行环境。请重新安装 GZWhisper。",
            "engine.missingVenvPython": "未找到应用虚拟环境中的 Python。",
            "engine.malformedResponse": "转写服务返回了无效响应。",
            "engine.modelMissing": "未找到本地模型。",
            "engine.invalidModelPath": "本地模型路径无效。",
            "engine.downloadingModel": "正在本地下载 Whisper large-v3-turbo...",
            "engine.validatingModel": "正在验证本地模型...",
            "engine.transcribing": "正在执行本地转写...",
            "engine.creatingVenv": "正在创建本地 Python 虚拟环境...",
            "engine.creatingVenvFailed": "创建虚拟环境失败。\n%@",
            "engine.installingDeps": "正在安装依赖（faster-whisper）...",
            "engine.installDepsFailed": "安装 Python 依赖失败。\n%@",
            "engine.offlineInstallFailed": "从内置离线包安装失败：\n%@",
            "engine.onlineInstallFailed": "通过 PyPI 在线安装失败：\n%@",
            "engine.noProcessOutput": "安装程序未返回诊断信息。",
            "process.cannotLaunch": "无法启动 %@：%@",
            "media.noAudioTrack": "此视频没有音频轨道。请选择包含音频的文件。",
            "media.exportUnavailable": "无法初始化从视频中提取音频。",
            "media.exportFailed": "提取音频失败：%@",
            "media.exportStatus": "导出状态：%d",
            "lang.auto": "自动",
            "lang.ru": "俄语",
            "lang.en": "英语",
            "lang.zh": "中文",
        ],
    ]

    static func t(_ key: String) -> String {
        strings[language]?[key] ?? strings[.en]?[key] ?? key
    }

    static func f(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), locale: Locale.current, arguments: args)
    }

    static var transcriptionLanguageOptions: [(title: String, code: String)] {
        [
            (t("lang.auto"), "auto"),
            (t("lang.ru"), "ru"),
            (t("lang.en"), "en"),
            (t("lang.zh"), "zh"),
        ]
    }
}
